In [1]:
1

1

In [2]:
[1:2, 3:4]

2-element Vector{UnitRange{Int64}}:
 1:2
 3:4

In [3]:
[1:2; 3:4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [4]:
[1:2 3:4 5:6]

2×3 Matrix{Int64}:
 1  3  5
 2  4  6

In [6]:
[zeros(Int64, 2, 2) [1; 2]
[3 4 5]]

3×3 Matrix{Int64}:
 0  0  1
 0  0  2
 3  4  5

In [7]:
[1 2 3
 4 5 6;;;
 7 8 9
 0 1 2]

2×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  2  3
 4  5  6

[:, :, 2] =
 7  8  9
 0  1  2

In [8]:
[1 2 ;;
 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [9]:
[1;;]

1×1 Matrix{Int64}:
 1

In [10]:
[2; 3;;;]

2×1×1 Array{Int64, 3}:
[:, :, 1] =
 2
 3

In [11]:
sum(1/n^2 for n = 1:1000)

1.6439345666815615

In [13]:
map(tuple, (1/(i+j) for i=1:2, j=1:2), [1:4;])

4-element Vector{Tuple{Float64, Int64}}:
 (0.5, 1)
 (0.3333333333333333, 2)
 (0.3333333333333333, 3)
 (0.25, 4)

In [15]:
[(i, j) for i=1:3 for j=1:i if i+j==4]

2-element Vector{Tuple{Int64, Int64}}:
 (2, 2)
 (3, 1)

In [16]:
A = reshape(collect(1:16), (2, 2, 2, 2))

2×2×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 1  3
 2  4

[:, :, 2, 1] =
 5  7
 6  8

[:, :, 1, 2] =
  9  11
 10  12

[:, :, 2, 2] =
 13  15
 14  16